name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4
        
      # 2. 构建步骤（关键修正点）
      - name: Build
        run: |
          mkdir -p public
          # 复制所有必要文件并保持结构
          cp src/index.html public/
          cp -r src/images public/
          cp -r src/js public/
          cp -r src/css public/
          
          # 验证复制结果（调试用）
          ls -R public

      # 3. 部署
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public   # 必须指向public目录
          keep_files: false       # 清理旧文件